### ISSUE TITLE
Sync product attributes

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#98] opened 2017-09-15 10:33 UTC
### Implementation details
1. Product types should be fetched and cached on-demand per batch.
2. Only some, but not the entire, information on Product types are needed to be fetched: 
 a. **Each attribute's `type`**: The types that we should be concerned with for the MVP are `BooleanType`, `TextType`, `LocalizableTextType`, `EnumType`, `LocalizableEnumType`, `NumberType` and `SetType`.
b. The `EnumType` and `LocalizableEnumType` values should not be cached since they are big and are not needed.
c. **`isRequired` field**: if the field is required but doesn't actually have a new value, the sync library would trigger the error call back instead of making a request to CTP.
d. **`attributeConstraint` field**: if it has the value `SameForAll`, then the `setAttributeInAllVariants` update action should be used for adding/removing/changing an attribute value at the same time for all the variants.

P.S. The name of every attribute is unique. 

### Hints 
`Product#masterData#staged#variants#attributes`

http://dev.commercetools.com/http-api-projects-products.html#attribute

### Update Actions required

1. [x] addVariant
2. [x] removeVariant
3. [x] changeMasterVariant
4. [x] setSku
5. [x] setAttribute
6. [x] setAttributeInAllVariants
7.  ~setProductVariantKey~

**Comment by andrii-kovalenko-ct** [comment] 2017-09-27 12:34
closed by #113

**Comment by ahmetoz** [comment] 2021-01-11 15:35
The issue looks like not managed after it's open. The changed described in the issue is already implemented.

**Closed by ahmetoz** 2021-01-11 15:35 UTC
Labels: product-sync, to-be-stabilised
