### ISSUE TITLE
create a dedicated util mapValuesToFutureOfListCompletedValues of of mapValuesToFutureOfCompletedValues

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#258] opened 2018-02-26 09:38 UTC
### Description
create a dedicated util `mapValuesToFutureOfListCompletedValues` of of `mapValuesToFutureOfCompletedValues`

Check comments: https://github.com/commercetools/commercetools-sync-java/pull/254#discussion_r170242219, https://github.com/commercetools/commercetools-sync-java/pull/254#discussion_r170244793

**Comment by ahmetoz** [comment] 2021-01-11 13:44
The issue should be managed/refactored as a boy-scout change next time when we are working on this utility next time, currently scope of the issue is not clear, therefore I'm closing it.

**Closed by ahmetoz** 2021-01-11 13:44 UTC
Labels: commons, enhancement :arrow_up:, good first issue, hacktoberfest, no-brainer
