### ISSUE TITLE
Refactor ClientConfigurationUtils

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#144] opened 2017-10-11 09:54 UTC
- [ ] Separate ClientConfigurationUtils that should be exposed (`createClient` should not be `synchronized` and not singleton). (should not have this client caching)
- [ ] ClientConfigurationUtils internal for the ITs should be synchronized and singletons with caching (add comments why synchronized and why caching)
- [ ] ~Make two versions of createClient: one that returns `BlockingClient` and one that returns normal client `sphereClient`.~ (Check comment: https://github.com/commercetools/commercetools-sync-java/issues/144#issuecomment-335789545)
    - [ ] Remove all `.toCompletebleFuture().join()` and `CompletionStageUtil` to` executeBlocking()`
- [ ] Exposed ClientConfigUtils to the user, should be
    - [ ] tested
    - [ ] JavaDoc'd
    - [ ] Usage READMEs should be updated

**Comment by butenkor** [comment] 2017-10-11 12:12
I wonder if `two version of createClient` are required. It might be only one version which returns `SphereClient` and on demand one can convert it into blocking one?

`BlockingSphereClient.of(sphereClient, Duration.ofMinutes(1));`

**Comment by heshamMassoud** [comment] 2017-10-11 12:45
Makes sense. Then the util would just be changed to returning an exact instance `sphereClient`. And the users can then convert to blocking on demand.

**Comment by ahmetoz** [comment] 2020-12-29 10:52
The issue is a bit outdated with the latest changes in the client, hereby I am closing the issue.

**Closed by ahmetoz** 2020-12-29 10:52 UTC
Labels: Feature :sparkles:, commons, enhancement :arrow_up:
